In [ ]:
#numpy : cross product of  two vectors 
import numpy as np
a = np.array([1,-7,7])
print (a)
b = np.array([3,-2,2])
print (b)
c = np.cross(a,b)
print ('cross product of two vectors a and b is :')
print (c)


[ 1 -7  7]
[ 3 -2  2]
cross product of two vectors a and b is :
[ 0 19 19]
