In [1]:
# importing the libraries 
import numpy as np 

In [20]:
# given matrix is A 
A=np.array([[4.,3.],[5.,-2.]])
print("Given matrix A : \n",A)

Given matrix A : 
 [[ 4.  3.]
 [ 5. -2.]]


In [21]:
Q=np.array([[4/np.sqrt(41),5/np.sqrt(41)],[5/np.sqrt(41),-4/np.sqrt(41)]])
R=np.array([[np.sqrt(41),2/np.sqrt(41)],[0,23/np.sqrt(41)]])
print("Orthogonal Matrix Q :\n",Q)
print("\nUpper Triangular Matrix R : \n",R)

Orthogonal Matrix Q :
 [[ 0.62469505  0.78086881]
 [ 0.78086881 -0.62469505]]

Upper Triangular Matrix R : 
 [[6.40312424 0.31234752]
 [0.         3.59199652]]


In [22]:
#QR Decomposition is given by 
Q@R

array([[ 4.,  3.],
       [ 5., -2.]])