In [13]:
# QR Decomposition   
import numpy as np
A=np.array([[4.,-3.],[6.,-2.]])
print("Given matrix A is: \n",A)
Q,R=np.linalg.qr(A)
print("\nOrthogonal Matrix Q is :\n",Q)
#Verification Q^TQ=I
print("\nQ^TQ:\n",Q.T@Q)

print("\nUpper Triangular Matrix R is: \n",R)
print("\nA=QR=\n",Q@R)

Given matrix A is: 
 [[ 4. -3.]
 [ 6. -2.]]

Orthogonal Matrix Q is :
 [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]

Q^TQ:
 [[ 1.0000000e+00 -1.0499512e-17]
 [-1.0499512e-17  1.0000000e+00]]

Upper Triangular Matrix R is: 
 [[-7.21110255  3.32820118]
 [ 0.          1.38675049]]

A=QR=
 [[ 4. -3.]
 [ 6. -2.]]
