##### Assignment 3 :

If F(x)=$\begin{pmatrix}
  \cos{x} & -\sin{x} & 0\\ 
  \sin{x} & \cos{x} & 0\\
  0 & 0 & 1
\end{pmatrix}$ 
Show that F(x)F(y)=F(x+y)

##### Python code:

In [32]:
import numpy as np 
import math
#for verification of answers we initialize x and y to particular value
x=30
y=60
f_x=np.array([[np.cos(x),-np.sin(x),0],[np.sin(x),np.cos(x),0],[0,0,1]])
f_x

array([[ 0.15425145,  0.98803162,  0.        ],
       [-0.98803162,  0.15425145,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [33]:
f_x.shape

(3, 3)

In [34]:
f_y=np.array([[np.cos(y),-np.sin(y),0],[np.sin(y),np.cos(y),0],[0,0,1]])
f_y

array([[-0.95241298,  0.30481062,  0.        ],
       [-0.30481062, -0.95241298,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [35]:
f_y.shape

(3, 3)

In [36]:
#LHS
f_lhs=np.matmul(f_x,f_y)
f_lhs#F(x)F(y)

array([[-0.44807362, -0.89399666,  0.        ],
       [ 0.89399666, -0.44807362,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [37]:
#RHS
f_rhs=np.array([[np.cos(x+y),-np.sin(x+y),0],[np.sin(x+y),np.cos(x+y),0],[0,0,1]])
f_rhs#F(x+y)

array([[-0.44807362, -0.89399666,  0.        ],
       [ 0.89399666, -0.44807362,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

- From the above two matrices , it is clear that F(x)F(y)=F(x+y)