In [32]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
from numpy import linalg as LA

In [33]:
M=np.matrix('3 -1; 2 -2; 6 -2')
b=np.matrix('5; -1; -1')
print("Matrix M : \n",M)
print("\nMatrix b:\n",b)

Matrix M : 
 [[ 3 -1]
 [ 2 -2]
 [ 6 -2]]

Matrix b:
 [[ 5]
 [-1]
 [-1]]


In [34]:
#SVD, M=USV^T
U, s, V=LA.svd(M)
#Find size of M
M.shape

(3, 2)

In [35]:
#Creating the singular matrix
S = np.zeros(M.shape)
Sinv = S.T
S[:2,:2] = np.diag(s)
#Verifying the SVD, A=USV
print(U.dot(S).dot(V.T))
print("Therefore M=USV^T")

[[ 3. -1.]
 [ 2. -2.]
 [ 6. -2.]]
Therefore M=USV^T


In [36]:
#Inverting s
sinv = 1./s
#Inverse transpose of S
Sinv[:2,:2] = np.diag(sinv)
#Moore-Penrose Pseudoinverse
a1=U.T.dot(b)
a2=Sinv.dot(x)
#Least squares solution
xls=V.dot(a2)#
print(xls)

[[0.55]
 [1.05]]


In [37]:
V

matrix([[-0.92870863,  0.37081031],
        [ 0.37081031,  0.92870863]])